config/routes.rb
Rails.application.routes.draw do

  # для входа админов через гем devise как админ
  devise_for :admins
  # роутинг для гема rails_admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # =====================================================================
  # тут определяем точки входа в систему
  # =====================================================================
  #
  # точка входа для неаутентифицированных пользователей
  # root 'events#index'
  # unauthenticated - это метод гема devise
  #+unauthenticated do
   root :to => 'events#index'
  #+end
  #
  # точка входа для админки
  #+get 'admin' => 'admins#index'
  #
  # рут для страницы инфо
  get '/about' => 'static_pages#about'
  # для rails_admin определяем вход через devise
  #devise_for :admin
  #
  # точка входа для аутентифицированных как :admins
  # authenticated - метод гема devise
  #+ authenticated do
  #  as :admins do
  #    root :to => 'admins#index'
  #  end
  #+end
  #
  #
  # точка входа для аутентифицированных как :user
  #+authenticated do 
  #+  as :user do
  #+    root :to => 'events#index'
  #+  end
  #+end
  #
  # =====================================================================
  # тут определяем роутинг для :admins
  # =====================================================================
  # для входа админов через гем devise как админ
  #+devise_for :admins
  #
  #+resources :admins, except: [:create, :update]
  # определяем post-запрос для создания админа другим админом
  #+post 'create_admin' => 'admins#create', as: :create_admin
  # определяем patch-запрос для редактирования админа другим админом
  # это было необходимо чтобы создать моршрут с :id для редактирования админа
  #+patch 'update_admin/:id' => 'admins#update', as: :update_admin
  # это было необходимо чтобы создать моршрут с :id для удаления админа
  #+delete 'destroy_admin/:id' => 'admins#destroy', as: :destroy_admin



  # используем пространство имен для админ панели
  #+namespace :admin do
    # создаем контроллер :content для управления всем контентом
  #+  resources :content
  #+end
    
  # =====================================================================
  # тут определяем роутинг для :users
  # =====================================================================
  # для гема devise
  devise_for :users
  
  resources :users, only: [:index, :show]

  # фикс для удаления фото: перенаправляем get запрос в метод destroy
  get '/events/:event_id/photos/:id' => 'photos#destroy'


  # ресурсы events
  resources :events do

    # вложенный ресурс comments
  	resources :comments, only: [:create, :destroy]
    # вложенный ресурс subscriptions
    resources :subscriptions, only: [:create, :destroy]
    # вложенный ресурс photos
    resources :photos, only: [:create, :destroy]
    # вложенный ресурс гугл-точек на карте
    resources :gmap_dots, only: [:create, :destroy]

    post :show, on: :member

  end

  # ресурс users
  resources :users, only: [:show, :edit, :update]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :event, presence: true
  validates :body, presence: true

  # поле должно быть только если не выполняется user.present?
  # т е у объекта не задан юзер
  validates :user_name, presence: true, unless: 'user.present?'

  # переопределяем метод, если есть юзер то выдаем его имя
  # если нет - то выполняем исходный переопределенный метод
  def user_name
  	if user.present?
  	  user.name
  	else
  	  super
  	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # задаем эвент, к которому принадлежит коммент (родительский евент)
  before_action :set_event, only: [:create, :destroy]

  # задаем сам коммент, который надо удалить
  before_action :set_comment, only: [:destroy]

  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user
    if @new_comment.save
      # уведомляем подписчиков о новом комментарии
      # notify_subscribers(@event, @new_comment)

      redirect_to @event, notice: 'Комментарий добавлен'
    else
      # render 'events/show', alert: I18n.t('controllers.comments.error')
      # redirect_to @event, alert: 'Каммент не добавлен'
      redirect_to @event, alert: 'Комментарий не добавлен'
    end
  end


  def destroy
    message = {notice: 'Комментарий удален'}

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = {alert: I18n.t('controllers.comment.error')}
    end
    redirect_to @event, message
  end




  private


  def set_event
  	@event = Event.find(params[:event_id])
  end


  def set_comment
  	@comment = @event.comments.find(params[:id])
  end


  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end



end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-bottom">

  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        <span>
        <% if comment.user.present? %>
          <%= render partial: 'users/user', object: comment.user %>
        <% else %>
          <em><strong><%= comment.user.name %></strong></em>
        <% end %>
      </span>

      <em><%= l comment.created_at, format: :short %></em>
        <% if current_user_can_edit?(comment) %>
          <%= link_to fa_icon('trash'), event_comment_path(comment.event, comment),
          method: :delete, data: {confirm: 'уверен что хочешь удалить комментарий?'} %>
        <% end %>
      </div>
    </div>

    <div class="panel-body">
      <h4><%= comment.body %></h4>
    </div>
  </div>
  
</div>

app/views/comments/_form.html.erb
<%= form_for [@event, comment] do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: comment} %>

  <div class="form-group">
    <%= f.label :body, 'Ваш каммент:' %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <% unless user_signed_in? %>
    <div class="form-group">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit 'Отправить', class: 'btn btn-primary' %>
  </div>

<% end %>