config/routes.rb
Rails.application.routes.draw do

  # для входа админов через гем devise как админ
  devise_for :admins
  # роутинг для гема rails_admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # =====================================================================
  # тут определяем точки входа в систему
  # =====================================================================
  #
  # точка входа для неаутентифицированных пользователей
  # root 'events#index'
  # unauthenticated - это метод гема devise
  #+unauthenticated do
   root :to => 'events#index'
  #+end
  #
  # точка входа для админки
  #+get 'admin' => 'admins#index'
  #
  # рут для страницы инфо
  get '/about' => 'static_pages#about'
  # для rails_admin определяем вход через devise
  #devise_for :admin
  #
  # точка входа для аутентифицированных как :admins
  # authenticated - метод гема devise
  #+ authenticated do
  #  as :admins do
  #    root :to => 'admins#index'
  #  end
  #+end
  #
  #
  # точка входа для аутентифицированных как :user
  #+authenticated do 
  #+  as :user do
  #+    root :to => 'events#index'
  #+  end
  #+end
  #
  # =====================================================================
  # тут определяем роутинг для :admins
  # =====================================================================
  # для входа админов через гем devise как админ
  #+devise_for :admins
  #
  #+resources :admins, except: [:create, :update]
  # определяем post-запрос для создания админа другим админом
  #+post 'create_admin' => 'admins#create', as: :create_admin
  # определяем patch-запрос для редактирования админа другим админом
  # это было необходимо чтобы создать моршрут с :id для редактирования админа
  #+patch 'update_admin/:id' => 'admins#update', as: :update_admin
  # это было необходимо чтобы создать моршрут с :id для удаления админа
  #+delete 'destroy_admin/:id' => 'admins#destroy', as: :destroy_admin



  # используем пространство имен для админ панели
  #+namespace :admin do
    # создаем контроллер :content для управления всем контентом
  #+  resources :content
  #+end
    
  # =====================================================================
  # тут определяем роутинг для :users
  # =====================================================================
  # для гема devise
  devise_for :users
  
  resources :users, only: [:index, :show]

  # фикс для удаления фото: перенаправляем get запрос в метод destroy
  get '/events/:event_id/photos/:id' => 'photos#destroy'


  # ресурсы events
  resources :events do

    # вложенный ресурс comments
  	resources :comments, only: [:create, :destroy]
    # вложенный ресурс subscriptions
    resources :subscriptions, only: [:create, :destroy]
    # вложенный ресурс photos
    resources :photos, only: [:create, :destroy]
    # вложенный ресурс гугл-точек на карте
    resources :gmap_dots, only: [:create, :destroy]

    post :show, on: :member

  end

  # ресурс users
  resources :users, only: [:show, :edit, :update]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise 	:database_authenticatable, 
  	  		:registerable,
         	:recoverable, 
         	:rememberable, 
         	:validatable,
          :trackable


  # юзер может создавать много событий
  has_many :events, dependent: :destroy
  # юзер может иметь много камментов
  has_many :comments, dependent: :destroy
  # юзер может иметь много подписок
  has_many :subscriptions, dependent: :destroy

  # связь dependent: :destroy выключена, 
  # если юзера удалить то фото должно все равно остаться
  has_many :photos

  # имеет много точек на карте (gmap_dots)
  has_many :gmap_dots

  # имя юзера должно быть, и не длиннее 30 букв
  validates :name, presence: true, length: {maximum: 30}

  # при создании нового юзера (метод create), 
  # перед валидацией объекта выполнить метод set_name
  # before_validation :set_name, on: :create

  # после коммита обновить подписки
#  after_commit :link_subscriptions, on: :create

  # Добавляем аплоадер аватарок, чтобы заработал carrierwave
  mount_uploader :avatar, AvatarUploader

  private

  # задаем юзеру случайное имя, если оно пустое
  def set_name
    self.name = "алик-#{rand(777)}" if name.blank?
  end

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: email).update_all(user_id: id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # перед действием проверяем аутентификацию юзера
  before_action :authenticate_user!, except: [:show]

  # задаем текущего юзера как объект @user для шаблонов и экшенов
  before_action :set_current_user, except: [:show]


  # GET /events
  def index
    # @comments_event_collection = @event.comments.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @events = Event.all
    @users = User.all.paginate(page: params[:page], per_page: 5)
  end


  # GET /users/1/
  def show
  	@user = User.find(params[:id])
    @comment = @user.comments.order(created_at: :desc).limit(5)
  end

  # GET /user/1/edit
  def edit
  end


  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Профиль обновлен'
    else
      render 'edit'
    end
  end


  private

  def set_current_user
  	@user = current_user
  end


  # пользователь в этом контроллере может менять имя, емейл
  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>

  <%= render partial: 'partials/form_errors', locals: {model: @user} %>

  <div class="form-group">
    <%= f.label :name, "имя" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email, "почта" %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar, "аватар" %>
    <%= image_tag(@user.avatar.thumb.url) if @user.avatar? %>
    <%= f.file_field :avatar %>
  </div>  

  <div class="actions">
    <%= f.submit 'Сохранить', class: "btn btn-primary" %> или <%= link_to 'вернуться', :back %>
  </div>

<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon img-circle', width: "50px") %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/_user_index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= link_to 'Профиль: ' + user.name, user_path(user), style: "color:white" %> 
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">
        <%= image_tag(user_avatar(user), class: 'img-icon img-circle', width: "100px") %>
      </div>
      <div class="col-md-5">
        Эл. почта:: <%= user.email %><br>
        Последний вход в систему: <%= user.current_sign_in_at %><br/>
        IP при последнем входе в систему: <%= user.current_sign_in_ip %><br/>
        Зарегистрировался: <%= user.created_at %><br/>
        Последнее обновление профиля: <%= user.updated_at %>
      </div>
      <div>
        Создано тем: <%= user.events.count %><br/>
        Написано комментариев: <%= user.comments.count %><br/>
        Загружено картинок: <%= user.photos.count %><br/>
        <small>подробнее <%= link_to 'см. профиль', user_path(user) %></small>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
  	
    <%= render 'form' %>


    <br/>
    <p class="buffer-top">
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<h1>Просмотр зарегистрированных пользователей:</h1>
<hr/>

<%= render partial: 'users/user_index', collection: @users, :as => :user %>

<div class="apple_pagination">
  <%= will_paginate @users %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="panel panel-primary">
    <div class="panel-heading">
      Пользователь: <%= @user.name %>
    </div>

    <div class="panel-body">
      <div class="col-md-4" id="avatar_user_show">
        <%= image_tag user_avatar(@user) %>
        <br/>
        <br/>

        <%# если это текущий пользователь то ему доступна ссылка "редактировать" %>
        <% if @user == current_user %>
          <p class="buffer-top">
            <%= link_to 'Редактировать профиль', edit_user_path(@user), class: "btn btn-default" %>
          </p>
        <% end %>

      </div>
   
      <div class="col-md-8">
        <h4>
          Имя: <%= @user.name %><br/>
          Эл. почта: <%= @user.email %><br>
          Последний вход в систему: <%= @user.current_sign_in_at %><br/>
          IP при последнем входе в систему: <%= @user.current_sign_in_ip %><br/>
          Зарегистрировался: <%= @user.created_at %><br/>
          Последнее обновление профиля: <%= @user.updated_at %><br/>
          Создано событий: <%= @user.events.count %><br/>
          Написано комментариев: <%= @user.comments.count %><br/>
          Загружено картинок: <%= @user.photos.count %><br/>
        </h4>
        <hr/>
        <ul class="list-group">
          <h4>5 последних комментариев:</h4>
          <% if @user.comments.any? %>
            <% @comment.each do |comment| %>
              <li class="list-group-item">
                <%= comment.body %><br/>
                <small>
                  <%= comment.created_at %>
                  <%= link_to '(Перейти)', event_path(comment.event_id) %>
                </small>
              </li>
            <% end %>
          <% else %>
            Этот пользователь не оставлял сообщений
          <% end %>
        </ul>
      </div>
    
    </div>
  </div>
      
    <%# показываем список событий, организованных данным пользователем %>

    <div class="row">
    	<div class="col-md-12">
    	  <% if @user.events.any? %>
    	    <h3>Организованы следующие события:</h3>
    	      <div class="row">
    	      	<%= render partial: 'events/event', collection: @user.events %>
    	      </div>
    	  <% else %>
    	     <p class="buffer-top">Пользователь не организовал ни одного события</p>
    	  <% end %>
    	</div>
    </div>

</div>