config/routes.rb
Rails.application.routes.draw do

  # для входа админов через гем devise как админ
  devise_for :admins
  # роутинг для гема rails_admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # =====================================================================
  # тут определяем точки входа в систему
  # =====================================================================
  #
  # точка входа для неаутентифицированных пользователей
  # root 'events#index'
  # unauthenticated - это метод гема devise
  #+unauthenticated do
   root :to => 'events#index'
  #+end
  #
  # точка входа для админки
  #+get 'admin' => 'admins#index'
  #
  # рут для страницы инфо
  get '/about' => 'static_pages#about'
  # для rails_admin определяем вход через devise
  #devise_for :admin
  #
  # точка входа для аутентифицированных как :admins
  # authenticated - метод гема devise
  #+ authenticated do
  #  as :admins do
  #    root :to => 'admins#index'
  #  end
  #+end
  #
  #
  # точка входа для аутентифицированных как :user
  #+authenticated do 
  #+  as :user do
  #+    root :to => 'events#index'
  #+  end
  #+end
  #
  # =====================================================================
  # тут определяем роутинг для :admins
  # =====================================================================
  # для входа админов через гем devise как админ
  #+devise_for :admins
  #
  #+resources :admins, except: [:create, :update]
  # определяем post-запрос для создания админа другим админом
  #+post 'create_admin' => 'admins#create', as: :create_admin
  # определяем patch-запрос для редактирования админа другим админом
  # это было необходимо чтобы создать моршрут с :id для редактирования админа
  #+patch 'update_admin/:id' => 'admins#update', as: :update_admin
  # это было необходимо чтобы создать моршрут с :id для удаления админа
  #+delete 'destroy_admin/:id' => 'admins#destroy', as: :destroy_admin



  # используем пространство имен для админ панели
  #+namespace :admin do
    # создаем контроллер :content для управления всем контентом
  #+  resources :content
  #+end
    
  # =====================================================================
  # тут определяем роутинг для :users
  # =====================================================================
  # для гема devise
  devise_for :users
  
  resources :users, only: [:index, :show]

  # фикс для удаления фото: перенаправляем get запрос в метод destroy
  get '/events/:event_id/photos/:id' => 'photos#destroy'


  # ресурсы events
  resources :events do

    # вложенный ресурс comments
  	resources :comments, only: [:create, :destroy]
    # вложенный ресурс subscriptions
    resources :subscriptions, only: [:create, :destroy]
    # вложенный ресурс photos
    resources :photos, only: [:create, :destroy]
    # вложенный ресурс гугл-точек на карте
    resources :gmap_dots, only: [:create, :destroy]

    post :show, on: :member

  end

  # ресурс users
  resources :users, only: [:show, :edit, :update]

end

app/models/event.rb
class Event < ApplicationRecord

  # настраиваем сортировку для модели в rails_admin
  rails_admin do 
    list do
      sort_by :created_at
      field :title
      field :description
      field :address
      field :datetime
    end
  end

   
  # событие принадлежит юзеру
  belongs_to :user

  # событие имеет много комментариев и подписок
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  # событие имеет много фоток
  has_many :photos, dependent: :destroy

  # имеет несколько точек на карте (gmap_dots)
  has_many :gmap_dots

  # у события много подписчиков (объекты User), 
  # через таблицу subscriptions, по ключу user_id
  has_many :subscribers, through: :subscriptions, source: :user

  # проверка, событие создает юзер. юзера не может не быть
  validates :user, presence: true
  # заголовок должен быть, и не длиннее 255 букв
  validates :title, presence: true, length: {maximum: 255}
  # всегда должен быть адрес и время
  validates :address, presence: true
  # пока закоммментировано datetime т к при создании эвента форма сама подставит текущую дату и время
  # а для rails_admin надо заставить работать форму даты/времени
  validates :datetime, presence: true


  # получаем список участников события
  # всех подписавшихся + организатора(создателя)
  def visitors
    (subscribers + [user]).uniq
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # проверить залогинен ли юзер, исключение - просмотр существующих евентов
  before_action :authenticate_user!, except: [:show, :index]

  # задаем объект @event для экшена show
  before_action :set_event, only: [:show]

  # задаем объект @event для текущего пользователя
  before_action :set_current_user_event, only: [:edit, :update, :destroy]

  # задаем коллекцию камментов для партиала
  before_action :set_comments_event_collection, only: [:show]

  
  # GET /events
  def index
  	@events = Event.all
  end


  # GET /events/1
  def new
  	@event = current_user.events.build
  end


  # POST /evebts
  def create
  	@event = current_user.events.build(event_params)

  	if @event.save
  	  redirect_to @event, notice: 'Событие успешно создано'
  	else
  	  render :new
  	end
  end


  def show
  # заготовка модели для добавления формы комментария
  @new_comment = @event.comments.build(params[:comment])

  # Заготовка модели для формы подписки
  @new_subscription = @event.subscriptions.build(params[:subscription])

  # Заготовки для загрузки фото
  @new_photo = @event.photos.build(params[:photo])

  # Заготовки для получения новой точки гугл-карты
  @new_gmap_dot = @event.gmap_dots.build(params[:gmap_dot])

  @dots_for_js = @event.gmap_dots

  end


  # GET /events/1/edit
  def edit
  
  end

  
  # PATCH/PUT /events/1
  def update
  	if @event.update(event_params)
  	  redirect_to @event, notice: 'Информация о событии была обновлена'
  	else
  	  render 'edit'
  	end
  end


  # DELETE /events/1
  def destroy
  	@event.destroy
  	redirect_to events_path, notice: 'Событие было удалено'
  end


  protected

  def event_params
  	params.require(:event).permit(:title, :address, :datetime, :description) # , :pincode)
  end


  def set_event
  	@event = Event.find(params[:id])
  end


  def set_current_user_event
  	@event = current_user.events.find(params[:id])
  end

  # получаем коллекцию камментов для партиала
  def set_comments_event_collection
    @comments_event_collection = @event.comments.except(@new_comment).paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<!-- Парnиал отображения инфы об отдельном событии -->

<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <%= content_tag 'div', '',
                    class: 'event-background',
                    style: "background-image: url(#{event_thumb(event)})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event), class: "event-title" %></h3>
          <h3>
            <%# Для перевода времени в русский формат используем I18n %>
            <%# Формат при этом используется из гема russian %>
            <small class="event-date"><%= l event.datetime, format: :short %></small>
          </h3>
          <div class="event-coords"><%= event.address %></div>
        </div>

        <div>
          <%# Выводим аватары юзеров, которые придут на событие %>
          <% event.visitors.each do |user| %>
            <%= image_tag(user_avatar_thumb(user), class: "img-circle", width: "50px", title: user.name) %>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_events.html.erb
<!-- Парnиал отображения инфы об отдельном событии -->
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
  	<%= content_tag 'div', '', 
  	  class: "event-background", 
  	  style: "background-image: url(#{event_thumb(event)})"  %>

  	  <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <%# Для перевода времени в русский формат используем I18n %>
            <%# Формат при этом используется из гема russian %>
            <small><%= l event.datetime, format: :short %></small>
          </h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <%# Выводим всех пользователей, которые придут на событие, выводя их аватарки %>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/events/_form.html.erb
<%= form_for(@event)  do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title, "Название события" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address, "Адрес проведения" %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime, "Время и дата" %>
    <%= f.datetime_select :datetime, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime, "Время и дата" %>
    <%= f.datetime_select :datetime, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Суть пьянки" %>
    <%= f.text_area :description, class: 'form-control', rows: "7" %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
  </div>

<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>

    <br/>

    <% if current_user_can_edit?(@event) %>
      <div class="buffer-both">
        <%= link_to 'Удалить событие', event_path(@event), method: :delete, class: "btn btn-danger", data: {confirm: 'Уверен что хочешь удалить встречу?'} %>
      </div>
    <% end %>
  
  </div>

</div>

app/views/events/index.html.erb
<h1>События и мероприятия</h1>

<div class="buffer-both">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>
<hr/>
<div class="row buffer-bottom">
  <!-- рендерим сразу все события, каждое в партиале 'events/event' -->
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
  	<%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  
  <div class="event-info row">
  	<div class="col-md-12">

      <%# Выводим произвольную фотку в качестве фона для шапки события %>
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})" %>
  	  
      <div class="event-info-inner row">
       	<div class="col-md-9">

       	  <div class="event-description-show">
       	  	<h1 class="event-title"><%= @event.title %></h1>
       	  	<%# для перевода даты в русский формат используем гем I18n %>
       	  	<%# формат при этом используется из гема russian %>
       	  	<h3><%= l @event.datetime, format: :short %></h3>
       	  	<h3>
       	  	  <small><%= @event.address %></small>
       	  	</h3>
       	  	<p><%= @event.description %></p>
       	  </div>

       	  <% if current_user_can_edit?(@event) %>
       	    <div class="buffer-both">
       	      <%= link_to 'Изменить', edit_event_path(@event), class: "btn btn-primary" %>
       	         	  
       	      <%#= link_to 'Удалить', event_path(@event), class: "btn btn-danger", method: :delete, data: {confirm: 'Уверен что хочешь удалить встречу?'} %>
       	    </div>
       	  <% end %>

       	</div>
      </div>

  	</div>
  </div>
  
  <br/>

  <div class="row">

    <div class="col-md-8">

      <!-- добавляем гугл карту -->
      <div class="row">
        <div id="map"></div>
      </div>

      <div>
        <% if current_user %>
          <%= link_to "Создать точку на карте", "#", class: 'event-gmap-dot-form-link' %>
          <div class='event-gmap-dot-form'>
            <%= render partial: 'gmaps/form_gmap', locals: {gmap_dot: @event.gmap_dots.build} %>
          </div>
        <% end %>
      </div>

      <br/>

      <div class="event-photos">
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>
        <%# кнопка вывода формы добавления фотографии %>
        <div class="buffer-both">
          <%= link_to "Добавить фотку", '#', class: 'event-photo-form-link' %>
        </div>

        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @event.photos.build} %>
        </div>
      </div>

      
      <%# Рисуем форму для добавления новой фотографии (которая будет скрыта с помощью js) %>
      <div class="event-comments buffer-top">
        <% if current_user %>
          <%= render partial: 'comments/form', 
                  locals: {comment: @event.comments.build} %>
        <% end %>
        <hr/>
        <div>
          <%= render partial: 'comments/comment', collection: @comments_event_collection %>
        </div>
      </div>

    </div>


    <div class="col-md-4">
      <div class="event-owner">
        <h4>Зовет:</h4>
        <p>
          <%= render partial: 'users/user', object: @event.user %>
        </p>
      </div>
      <div class="event-subscriptions">
        <h4>
          Пойдут:
        </h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
            collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <div class="event-subscription-form">
        <% if current_user %>
          <h4>Я пойду:</h4>
            <div>
              <%= render partial: 'subscriptions/form', 
                      locals: {subscription: @new_subscription || @event.subscriptions.build} %>
            </div>
        <% end %>
      </div>

      <br/>

    </div>

  </div>

</div>


<!-- пагинация -->
<div class="apple_pagination">
  <%= will_paginate @comments_event_collection %>
</div>


<!-- подключение lightbox2-rails -->
<%= javascript_include_tag 'lightbox' %>
<%= stylesheet_link_tag 'lightbox', :media => "all" %>



<!-- подключение яваскрипта отображения координат и карты -->
        
<%= render 'gmaps/event_gmap' %>


 
<script>

  /* показываем/скрываем форму загрузки для фотографий */
  $(function(){
    $('.event-photo-form').hide();

    $('.event-photo-form-link').click(function(){
      $('.event-photo-form').slideToggle(300);
      return false;
    });
  });

  
  /* показать/скрыть форму создания точки на карте */

  $(function(){
    $('.event-gmap-dot-form').hide();

    $('.event-gmap-dot-form-link').click(function(){
      $('.event-gmap-dot-form').slideToggle(300);
      return false;
    });
  });

</script>