config/routes.rb
Rails.application.routes.draw do

  # для входа админов через гем devise как админ
  devise_for :admins
  # роутинг для гема rails_admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # =====================================================================
  # тут определяем точки входа в систему
  # =====================================================================
  #
  # точка входа для неаутентифицированных пользователей
  # root 'events#index'
  # unauthenticated - это метод гема devise
  #+unauthenticated do
   root :to => 'events#index'
  #+end
  #
  # точка входа для админки
  #+get 'admin' => 'admins#index'
  #
  # рут для страницы инфо
  get '/about' => 'static_pages#about'
  # для rails_admin определяем вход через devise
  #devise_for :admin
  #
  # точка входа для аутентифицированных как :admins
  # authenticated - метод гема devise
  #+ authenticated do
  #  as :admins do
  #    root :to => 'admins#index'
  #  end
  #+end
  #
  #
  # точка входа для аутентифицированных как :user
  #+authenticated do 
  #+  as :user do
  #+    root :to => 'events#index'
  #+  end
  #+end
  #
  # =====================================================================
  # тут определяем роутинг для :admins
  # =====================================================================
  # для входа админов через гем devise как админ
  #+devise_for :admins
  #
  #+resources :admins, except: [:create, :update]
  # определяем post-запрос для создания админа другим админом
  #+post 'create_admin' => 'admins#create', as: :create_admin
  # определяем patch-запрос для редактирования админа другим админом
  # это было необходимо чтобы создать моршрут с :id для редактирования админа
  #+patch 'update_admin/:id' => 'admins#update', as: :update_admin
  # это было необходимо чтобы создать моршрут с :id для удаления админа
  #+delete 'destroy_admin/:id' => 'admins#destroy', as: :destroy_admin



  # используем пространство имен для админ панели
  #+namespace :admin do
    # создаем контроллер :content для управления всем контентом
  #+  resources :content
  #+end
    
  # =====================================================================
  # тут определяем роутинг для :users
  # =====================================================================
  # для гема devise
  devise_for :users
  
  resources :users, only: [:index, :show]

  # фикс для удаления фото: перенаправляем get запрос в метод destroy
  get '/events/:event_id/photos/:id' => 'photos#destroy'


  # ресурсы events
  resources :events do

    # вложенный ресурс comments
  	resources :comments, only: [:create, :destroy]
    # вложенный ресурс subscriptions
    resources :subscriptions, only: [:create, :destroy]
    # вложенный ресурс photos
    resources :photos, only: [:create, :destroy]
    # вложенный ресурс гугл-точек на карте
    resources :gmap_dots, only: [:create, :destroy]

    post :show, on: :member

  end

  # ресурс users
  resources :users, only: [:show, :edit, :update]

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%# Для вывода названия приложения используем хелпер I18n.t %>

    <%= link_to (image_tag 'favicon1.png', class: 'navbar-brand-image'), root_path, class: 'navbar-brand' %>
    <%= link_to 'GoDrink', root_path, class: 'navbar-brand', color: "#ff0033" %>
 
    <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Профиль <%= current_user.name %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Мой профиль', current_user %></li>
              <li><%= link_to 'Просмотр всех пользователей', users_path %></li>
            </ul>
          </li>
          <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Войти', new_user_session_path %></li>
          <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
        <% end %>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Инфо', about_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoDrinK</title>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= favicon_link_tag 'favicon1.png' %>

    <!-- скрипт для подключения гугл-карты c api_key -->
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyDPyioBlkPsV9FVfObr7TNwvlwE4pFzSEQ "></script>
    <script src="gmaps.js"></script>
    <style type="text/css">
      #map {
        width: 400px;
        height: 400px;
      }
    </style>
    <!-- старый плагин -->
    <!-- <script src="https://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.22&key=AIzaSyC5Uk2Oq2-Mzeh7Got8zgn-Qga-Mspcr1g"> 
    </script> -->
   
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">

          <% if notice != nil %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert != nil %>
            <p class="alert alert-error alert-danger"><%= alert %></p>
          <% end %>
          
          <%= yield %>

        </div>
      </div>

      <hr/>
      <%= debug(params) if Rails.env.development? %> 

    </div>




    <footer>
      <div class="navbar-fixed-bottom row-fluid">
        <div class="navbar-inner">
          <div class="container">
            <p>&copy; Developed for TKM's drinkers 2017, ver. 0.1.2</p>
          </div>
        </div>
      </div>
    </footer>
  
  </body>
</html>